### ISSUE TITLE
no space

### ISSUE THREAD

**Issue by paulmarique** [lipsumar/automotron#2]
C'est impossible pour le moment de mettre un point seul à la fin d'une phrase, sans que le générateur ajoute un espace.

![image](https://user-images.githubusercontent.com/11415856/67278747-e3dc9a00-f4c9-11e9-9267-ddc2249ef6d1.png)

**Comment by lipsumar** [comment]
En effet, l'automotron rassemble tous les conteneurs en les séparant par un point. à terme les connections pourront dire "avec ou sans espace"

**Comment by lipsumar** [comment]
it should be possible to control the separating characters between containers

ideas:

connections could have a "separator" attribute, a space, nothing or anything else
a new node "no space" to put between containers

**Comment by lipsumar** [comment]
landed in v1.4.0

a link by default has a separator "space". right click on a link allows to remove the space
